name: Weather Cache Update

on:
  schedule:
    # Runs every hour at minute 0
    - cron: '0 * * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  update-weather:
    runs-on: ubuntu-latest
    steps:
      - name: Call Weather Update Endpoint
        run: |
          curl -X POST "https://ladder-schedule.vercel.app/api/cron/weather" \
            -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}" \
            -H "Content-Type: application/json"